# Generated by Django 4.2.1 on 2023-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(max_length=32, verbose_name='Apellido Paterno')),
                ('apellidoMaterno', models.CharField(max_length=32, verbose_name='Apellido Materno')),
                ('correo', models.CharField(max_length=32, verbose_name='Correo Electronico')),
                ('comentarios', models.CharField(max_length=100, verbose_name='Comentarios')),
                ('creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Mensaje')),
            ],
        ),
    ]
